### 1. El Interesado hace una consulta (Público)
POST http://localhost:3000/properties/1/comments
Content-Type: application/json

{
  "nombreSolicitante": "Aron",
  "pregunta": "Hola, aceptan mascotas?"
}

### 2. Te logueás como el Vendedor para obtener el Token JWT
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "juan@inmobiliaria.com",
  "password": "123456"
}

### Extraemos el token a una variable automatica
@token = {{login.response.body.token}}


### 3. Revisás tu buzón de preguntas pendientes (Privado)
GET http://localhost:3000/api/vendedor/comentarios?sinResponder=true
Authorization: Bearer {{token}}


### 4. Respondés la consulta ID 1 (Privado)
PUT http://localhost:3000/api/vendedor/comentarios/1/respuesta
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "respuestaVendedor": "¡Hola Aron! Sí, somos súper pet-friendly."
}
