### 1. El Interesado pide una visita (Público)
POST http://localhost:3000/properties/1/visits
Content-Type: application/json

{
  "nombreVisitante": "Aron",
  "apellidoVisitante": "Gomez",
  "telefonoVisitante": "1122334455",
  "fechaPropuesta": "2026-12-15T10:00:00.000Z",
  "mensajeAsociado": "Me gustaría ver la casa por la mañana."
}

### 2. Login de Vendedor
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "juan@inmobiliaria.com",
  "password": "123456"
}

### Extraemos el token a una variable
@token = {{login.response.body.token}}

### 3. El vendedor revisa todas las visitas de su inmobiliaria
GET http://localhost:3000/api/vendedor/visitas
Authorization: Bearer {{token}}

### 3.b (Opcional) Revisar solo las pendientes
GET http://localhost:3000/api/vendedor/visitas?estado=PENDIENTE
Authorization: Bearer {{token}}

### 4. El vendedor confirma la visita ID 1
PUT http://localhost:3000/api/vendedor/visitas/1/estado
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "estado": "CONFIRMADA"
}
