### 1. Login Vendedor
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "juan@inmobiliaria.com",
  "password": "123456"
}

### Extraer Token
@token = {{login.response.body.token}}


### 2. Obtener Dashboard de Reportes Analíticos (Privado)
GET http://localhost:3000/api/vendedor/reportes
Authorization: Bearer {{token}}
